name: Monthly job

on:
  schedule:
  - cron: "22 10 2 * *"   # montly job - at "random" time - top of hour can be busy in github

jobs:
  sstate-cache-cleanup:
    if: github.repository == 'qualcomm-linux/meta-qcom'
    runs-on: [self-hosted, qcom-u2404, amd64-ssd]
    steps:
      - name: Clean up the persistant sstate-cache dir
        run: |
          # keep current and last month to allow smooth end of month transition
          rm -rf /efs/qli/meta-qcom/sstate-cache-$(date -d '2 months ago' '+%Y-%m')
